### PR TITLE
Fix travis setup to work with go modules

### PR DESCRIPTION
**Pull request by joac**
Just to get the build passing again!

I followed: 
https://dave.cheney.net/2018/07/16/using-go-modules-with-travis-ci
and:
https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/

### CODE REVIEW

**Comment by hoenirvili** [comment]
@joac I think you also need to sign the licence/cla agreement.

**Comment by hoenirvili** [comment]
@mitchellh Could you please review this?

**Comment by jefferai** [comment]
Unfortunately we need the CLA signed before we can proceed.

**Comment by hoenirvili** [comment]
@jefferai I know this PR is old, I could sign the CLA and then open a separate PR including these changes.

**Comment by joac** [comment]
Done, sorry for the delay

**Comment by hoenirvili** [comment]
@joac It stills says that the licence/cla is pending. Are you sure that you sign the agreement?

**Comment by joac** [comment]
I signed it, but is not updating :(

**Comment by hoenirvili** [comment]
@jefferai How can this issue with the license can be resolved in order to merge this?

**Comment by jefferai** [comment]
Sorry about that, I've poked the responsible people, hopefully it will be resolved on Monday

**Comment by jfreda** [comment]
👋 Hi @joac ! Can you please make sure that the email address that you used to author your PR commit is associated with your GitHub user? You might either need to add it to your GitHub email settings or rebase to create a different commit with a valid email address so the CLA check goes through. Thanks!

**Pull request closed without merging**
